function result = heat_demo(gridSize, numSteps, ratio)
%HEAT_DEMO 为浏览器返回热扩散数值，不执行发布或图片导出。
    [initial, ~, ~, ambient] = initial_temperature_demo(gridSize);
    simulation = simulate_heat_diffusion_demo( ...
        initial, ambient, ratio, numSteps, [0, numSteps]);
    % 运行器的大数组可能复用输入存储；重新生成确定性的初始图。
    initialForPlot = initial_temperature_demo(gridSize);
    halfTarget = ambient + 0.5 * (simulation.peak(1) - ambient);
    halfIndex = find(simulation.peak <= halfTarget, 1);
    halfCoolingStep = -1;
    if ~isempty(halfIndex)
        halfCoolingStep = halfIndex - 1;
    end
    result = struct( ...
        'gridSize', gridSize, 'numSteps', numSteps, 'ratio', ratio, ...
        'ambient', ambient, ...
        'initial', initialForPlot, ...
        'final', simulation.finalTemperature, ...
        'steps', simulation.steps, ...
        'peak', simulation.peak, ...
        'mean', simulation.meanTemperature, ...
        'energy', simulation.energy, ...
        'initialPeak', simulation.peak(1), ...
        'finalPeak', simulation.peak(numSteps + 1), ...
        'halfCoolingStep', halfCoolingStep, ...
        'energyRetainedPercent', 100 * simulation.energy(numSteps + 1) / simulation.energy(1));
end
